using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MvcCms.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<CmsEntities>
    {
        protected override void Seed(CmsEntities context)
        {
            var tags = new List<Tag>
            {
                new Tag { Name = "Rock" },
                new Tag { Name = "Jazz" },
                new Tag { Name = "Metal" },
                new Tag { Name = "Alternative" },
                new Tag { Name = "Disco" },
                new Tag { Name = "Blues" },
                new Tag { Name = "Latin" },
                new Tag { Name = "Reggae" },
                new Tag { Name = "Pop" },
                new Tag { Name = "Classical" }
            };

            var authors = new List<Author>
            {
                new Author { Name = "Aaron Copland & London Symphony Orchestra" },
                new Author { Name = "Aaron Goldberg" },
                new Author { Name = "AC/DC" },
                new Author { Name = "Accept" },
                new Author { Name = "Adrian Leaper & Doreen de Feis" },
                new Author { Name = "Aerosmith" },
                new Author { Name = "Aisha Duo" },
                new Author { Name = "Alanis Morissette" },
                new Author { Name = "Alberto Turco & Nova Schola Gregoriana" },
                new Author { Name = "Alice In Chains" },
                new Author { Name = "Amy Winehouse" },
                new Author { Name = "Anita Ward" },
                new Author { Name = "Antônio Carlos Jobim" },
                new Author { Name = "Apocalyptica" },
                new Author { Name = "Audioslave" },
                new Author { Name = "Barry Wordsworth & BBC Concert Orchestra" },
                new Author { Name = "Berliner Philharmoniker & Hans Rosbaud" },
                new Author { Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Author { Name = "Billy Cobham" },
                new Author { Name = "Black Label Society" },
                new Author { Name = "Black Sabbath" },
                new Author { Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Author { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Author { Name = "Bruce Dickinson" },
                new Author { Name = "Buddy Guy" },
                new Author { Name = "Caetano Veloso" },
                new Author { Name = "Cake" },
                new Author { Name = "Calexico" },
                new Author { Name = "Cássia Eller" },
                new Author { Name = "Chic" },
                new Author { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Author { Name = "Chico Buarque" },
                new Author { Name = "Chico Science & Nação Zumbi" },
                new Author { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Author { Name = "Chris Cornell" },
                new Author { Name = "Christopher O'Riley" },
                new Author { Name = "Cidade Negra" },
                new Author { Name = "Cláudio Zoli" },
                new Author { Name = "Creedence Clearwater Revival" },
                new Author { Name = "David Coverdale" },
                new Author { Name = "Deep Purple" },
                new Author { Name = "Dennis Chambers" },
                new Author { Name = "Djavan" },
                new Author { Name = "Donna Summer" },
                new Author { Name = "Dread Zeppelin" },
                new Author { Name = "Ed Motta" },
                new Author { Name = "Edo de Waart & San Francisco Symphony" },
                new Author { Name = "Elis Regina" },
                new Author { Name = "English Concert & Trevor Pinnock" },
                new Author { Name = "Eric Clapton" },
                new Author { Name = "Eugene Ormandy" },
                new Author { Name = "Faith No More" },
                new Author { Name = "Falamansa" },
                new Author { Name = "Foo Fighters" },
                new Author { Name = "Frank Zappa & Captain Beefheart" },
                new Author { Name = "Fretwork" },
                new Author { Name = "Funk Como Le Gusta" },
                new Author { Name = "Gerald Moore" },
                new Author { Name = "Gilberto Gil" },
                new Author { Name = "Godsmack" },
                new Author { Name = "Gonzaguinha" },
                new Author { Name = "Göteborgs Symfoniker & Neeme Järvi" },
                new Author { Name = "Guns N' Roses" },
                new Author { Name = "Gustav Mahler" },
                new Author { Name = "Incognito" },
                new Author { Name = "Iron Maiden" },
                new Author { Name = "James Levine" },
                new Author { Name = "Jamiroquai" },
                new Author { Name = "Jimi Hendrix" },
                new Author { Name = "Joe Satriani" },
                new Author { Name = "Jorge Ben" },
                new Author { Name = "Jota Quest" },
                new Author { Name = "Judas Priest" },
                new Author { Name = "Julian Bream" },
                new Author { Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Author { Name = "Kiss" },
                new Author { Name = "Led Zeppelin" },
                new Author { Name = "Legião Urbana" },
                new Author { Name = "Lenny Kravitz" },
                new Author { Name = "Les Arts Florissants & William Christie" },
                new Author { Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Author { Name = "Luciana Souza/Romero Lubambo" },
                new Author { Name = "Lulu Santos" },
                new Author { Name = "Marcos Valle" },
                new Author { Name = "Marillion" },
                new Author { Name = "Marisa Monte" },
                new Author { Name = "Martin Roscoe" },
                new Author { Name = "Maurizio Pollini" },
                new Author { Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Author { Name = "Men At Work" },
                new Author { Name = "Metallica" },
                new Author { Name = "Michael Tilson Thomas & San Francisco Symphony" },
                new Author { Name = "Miles Davis" },
                new Author { Name = "Milton Nascimento" },
                new Author { Name = "Mötley Crüe" },
                new Author { Name = "Motörhead" },
                new Author { Name = "Nash Ensemble" },
                new Author { Name = "Nicolaus Esterhazy Sinfonia" },
                new Author { Name = "Nirvana" },
                new Author { Name = "O Terço" },
                new Author { Name = "Olodum" },
                new Author { Name = "Orchestra of The Age of Enlightenment" },
                new Author { Name = "Os Paralamas Do Sucesso" },
                new Author { Name = "Ozzy Osbourne" },
                new Author { Name = "Page & Plant" },
                new Author { Name = "Paul D'Ianno" },
                new Author { Name = "Pearl Jam" },
                new Author { Name = "Pink Floyd" },
                new Author { Name = "Queen" },
                new Author { Name = "R.E.M." },
                new Author { Name = "Raul Seixas" },
                new Author { Name = "Red Hot Chili Peppers" },
                new Author { Name = "Roger Norrington, London Classical Players" },
                new Author { Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Author { Name = "Rush" },
                new Author { Name = "Santana" },
                new Author { Name = "Scholars Baroque Ensemble" },
                new Author { Name = "Scorpions" },
                new Author { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Author { Name = "Sir Georg Solti & Wiener Philharmoniker" },
                new Author { Name = "Skank" },
                new Author { Name = "Soundgarden" },
                new Author { Name = "Spyro Gyra" },
                new Author { Name = "Stevie Ray Vaughan & Double Trouble" },
                new Author { Name = "Stone Temple Pilots" },
                new Author { Name = "System Of A Down" },
                new Author { Name = "Temple of the Dog" },
                new Author { Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Author { Name = "The 12 Cellists of The Berlin Philharmonic" },
                new Author { Name = "The Black Crowes" },
                new Author { Name = "The Cult" },
                new Author { Name = "The Doors" },
                new Author { Name = "The King's Singers" },
                new Author { Name = "The Police" },
                new Author { Name = "The Posies" },
                new Author { Name = "The Rolling Stones" },
                new Author { Name = "The Who" },
                new Author { Name = "Tim Maia" },
                new Author { Name = "Ton Koopman" },
                new Author { Name = "U2" },
                new Author { Name = "UB40" },
                new Author { Name = "Van Halen" },
                new Author { Name = "Various authors" },
                new Author { Name = "Velvet Revolver" },
                new Author { Name = "Vinícius De Moraes" },
                new Author { Name = "Wilhelm Kempff" },
                new Author { Name = "Yehudi Menuhin" },
                new Author { Name = "Yo-Yo Ma" },
                new Author { Name = "Zeca Pagodinho" }
            };

            new List<Post>
            {
                new Post { Title = "A Copland Celebration, Vol. I", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Worlds", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aaron Goldberg"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "For Those About To Rock We Salute You", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "AC/DC"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Let There Be Rock", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "AC/DC"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Balls to the Wall", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Accept"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Restless and Wild", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Accept"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Górecki: Symphony No. 3", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Adrian Leaper & Doreen de Feis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Big Ones", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aerosmith"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Quiet Songs", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aisha Duo"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Jagged Little Pill", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Alanis Morissette"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Facelift", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Alice In Chains"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Frank", Tag = tags.Single(g => g.Name == "Pop"), Price = 8.99M, Author = authors.Single(a => a.Name == "Amy Winehouse"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Ring My Bell", Tag = tags.Single(g => g.Name == "Disco"), Price = 8.99M, Author = authors.Single(a => a.Name == "Anita Ward"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Chill: Brazil (Disc 2)", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Antônio Carlos Jobim"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Warner 25 Anos", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Antônio Carlos Jobim"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Plays Metallica By Four Cellos", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Apocalyptica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Revelations", Tag = tags.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Audioslave"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Audioslave", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Audioslave"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Last Night of the Proms", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Sibelius: Finlandia", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Mozart: Symphonies Nos. 40 & 41", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Best Of Billy Cobham", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Billy Cobham"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Alcohol Fueled Brewtality Live! [Disc 1]", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Label Society"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Alcohol Fueled Brewtality Live! [Disc 2]", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Label Society"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Black Sabbath Vol. 4 (Remaster)", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Sabbath"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Black Sabbath", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Sabbath"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Carmina Burana", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "A Soprano Inspired", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Chemical Wedding", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Bruce Dickinson"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Prenda Minha", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Caetano Veloso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Sozinho Remix Ao Vivo", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Caetano Veloso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Cake: B-Sides and Rarities", Tag = tags.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cake"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Carried to Dust (Bonus Track Version)", Tag = tags.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Calexico"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Cássia Eller - Sem Limite [Disc 1]", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cássia Eller"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Le Freak", Tag = tags.Single(g => g.Name == "Disco"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chic"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Scheherazade", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Minha Historia", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Buarque"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Afrociberdelia", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Science & Nação Zumbi"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Da Lama Ao Caos", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Science & Nação Zumbi"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Carry On", Tag = tags.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chris Cornell"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "SCRIABIN: Vers la flamme", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Christopher O'Riley"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Acústico MTV [Live]", Tag = tags.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cidade Negra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Cidade Negra - Hits", Tag = tags.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cidade Negra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Na Pista", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cláudio Zoli"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Chronicle, Vol. 1", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Creedence Clearwater Revival"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Chronicle, Vol. 2", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Creedence Clearwater Revival"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Into The Light", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "David Coverdale"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Come Taste The Band", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Deep Purple In Rock", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Fireball", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Machine Head", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "MK III The Final Concerts [Disc 1]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Purpendicular", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Slaves And Masters", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Stormbringer", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Battle Rages On", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Final Concerts (Disc 2)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Outbreak", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dennis Chambers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Djavan Ao Vivo - Vol. 02", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Djavan"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Djavan Ao Vivo - Vol. 1", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Djavan"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "MacArthur Park Suite", Tag = tags.Single(g => g.Name == "Disco"), Price = 8.99M, Author = authors.Single(a => a.Name == "Donna Summer"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Un-Led-Ed", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dread Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Best of Ed Motta", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ed Motta"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Adams, John: The Chairman Dances", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Edo de Waart & San Francisco Symphony"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Elis Regina-Minha História", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Elis Regina"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Pachelbel: Canon & Gigue", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "English Concert & Trevor Pinnock"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Unplugged", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eric Clapton"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Cream Of Clapton", Tag = tags.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eric Clapton"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Unplugged", Tag = tags.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eric Clapton"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Respighi:Pines of Rome", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eugene Ormandy"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Strauss: Waltzes", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eugene Ormandy"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "King For A Day Fool For A Lifetime", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Faith No More"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Deixa Entrar", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Falamansa"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "In Your Honor [Disc 1]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Foo Fighters"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "In Your Honor [Disc 2]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Foo Fighters"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Colour And The Shape", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Foo Fighters"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bongo Fury", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Frank Zappa & Captain Beefheart"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Roda De Funk", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Funk Como Le Gusta"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Quanta Gente Veio Ver (Live)", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Gilberto Gil"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Quanta Gente Veio ver--Bônus De Carnaval", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Gilberto Gil"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Faceless", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Godsmack"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Meus Momentos", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Gonzaguinha"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Nielsen: The Six Symphonies", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Appetite for Destruction", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guns N' Roses"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Use Your Illusion I", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guns N' Roses"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Use Your Illusion II", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guns N' Roses"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Blue Moods", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Incognito"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "A Matter of Life and Death", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Brave New World", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Fear Of The Dark", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Live At Donington 1992 (Disc 1)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Live At Donington 1992 (Disc 2)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Rock In Rio [CD2]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Number of The Beast", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The X Factor", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Virtual XI", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "A Real Dead One", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "A Real Live One", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Live After Death", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "No Prayer For The Dying", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Piece Of Mind", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Powerslave", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Rock In Rio [CD1]", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Rock In Rio [CD2]", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Seventh Son of a Seventh Son", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Somewhere in Time", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Number of The Beast", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Iron Maiden", Tag = tags.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Mascagni: Cavalleria Rusticana", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "James Levine"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Emergency On Planet Earth", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jamiroquai"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Are You Experienced?", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jimi Hendrix"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Surfing with the Alien (Remastered)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Joe Satriani"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Jorge Ben Jor 25 Anos", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jorge Ben"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Jota Quest-1995", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jota Quest"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Living After Midnight", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Judas Priest"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Weill: The Seven Deadly Sins", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Greatest Kiss", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Kiss"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Unplugged [Live]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Kiss"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "BBC Sessions [Disc 1] [Live]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "BBC Sessions [Disc 2] [Live]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Coda", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Houses Of The Holy", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "In Through The Out Door", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "IV", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Led Zeppelin I", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Led Zeppelin II", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Led Zeppelin III", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Physical Graffiti [Disc 1]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Physical Graffiti [Disc 2]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Presence", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Song Remains The Same (Disc 1)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Song Remains The Same (Disc 2)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Mais Do Mesmo", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Legião Urbana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Greatest Hits", Tag = tags.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Greatest Hits", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Greatest Hits", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Tchaikovsky: The Nutcracker", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Duos II", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Luciana Souza/Romero Lubambo"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Chill: Brazil (Disc 1)", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marcos Valle"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Misplaced Childhood", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marillion"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Barulhinho Bom", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marisa Monte"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Szymanowski: Piano Works, Vol. 1", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Martin Roscoe"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Best Of Men At Work", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Men At Work"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "...And Justice For All", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Black Post", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Garage Inc. (Disc 1)", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Garage Inc. (Disc 2)", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Load", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Master Of Puppets", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "ReLoad", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Ride The Lightning", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "St. Anger", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Berlioz: Symphonie Fantastique", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Prokofiev: Romeo & Juliet", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Miles Ahead", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Essential Miles Davis [Disc 1]", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Essential Miles Davis [Disc 2]", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Milton Nascimento Ao Vivo", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Milton Nascimento"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Minas", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Milton Nascimento"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Motley Crue Greatest Hits", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Mötley Crüe"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Ace Of Spades", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Motörhead"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Mozart: Chamber Music", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nash Ensemble"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Best of Beethoven", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Nevermind", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nirvana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Compositores", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "O Terço"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Olodum", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Olodum"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bach: The Brandenburg Concertos", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Acústico MTV", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Arquivo II", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Arquivo Os Paralamas Do Sucesso", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Tribute", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bark at the Moon (Remastered)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Blizzard of Ozz", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Diary of a Madman (Remastered)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "No More Tears (Remastered)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Speak of the Devil", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Walking Into Clarksdale", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Page & Plant"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Beast Live", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Paul D'Ianno"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Live On Two Legs [Live]", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Riot Act", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Ten", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Vs.", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Dark Side Of The Moon", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pink Floyd"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Greatest Hits I", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Greatest Hits II", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "News Of The World", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "New Adventures In Hi-Fi", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "R.E.M."), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Raul Seixas", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Raul Seixas"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "By The Way", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Red Hot Chili Peppers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Californication", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Red Hot Chili Peppers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Purcell: The Fairy Queen", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Roger Norrington, London Classical Players"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Haydn: Symphonies 99 - 104", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Retrospective I (1974-1980)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Rush"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Santana - As Years Go By", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Santana Live", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Supernatural", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Handel: The Messiah (Highlights)", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Scholars Baroque Ensemble"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Prokofiev: Symphony No.1", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Wagner: Favourite Overtures", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Maquinarama", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Skank"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "O Samba Poconé", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Skank"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "A-Sides", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Soundgarden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Heart of the Night", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Spyro Gyra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Morning Dance", Tag = tags.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Spyro Gyra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "In Step", Tag = tags.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Core", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Stone Temple Pilots"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Mezmerize", Tag = tags.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "System Of A Down"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Temple of the Dog", Tag = tags.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Temple of the Dog"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "[1997] Black Light Syndrome", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "South American Getaway", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Live [Disc 1]", Tag = tags.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Black Crowes"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Live [Disc 2]", Tag = tags.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Black Crowes"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Beyond Good And Evil", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Cult"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Doors", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Doors"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "English Renaissance", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "The King's Singers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Police Greatest Hits", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Police"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Every Kind of Light", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Posies"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Hot Rocks, 1964-1971 (Disc 1)", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "No Security", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Voodoo Lounge", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "My Generation - The Very Best Of The Who", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Who"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Serie Sem Limite (Disc 1)", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Tim Maia"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Serie Sem Limite (Disc 2)", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Tim Maia"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bach: Toccata & Fugue in D Minor", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ton Koopman"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Achtung Baby", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "B-Sides 1980-1990", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "How To Dismantle An Atomic Bomb", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Pop", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Rattle And Hum", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Best Of 1980-1990", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "War", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Zooropa", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "UB40 The Best Of - Volume Two [UK]", Tag = tags.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "UB40"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Diver Down", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "The Best Of Van Halen, Vol. I", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Van Halen III", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Van Halen", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Axé Bahia 2001", Tag = tags.Single(g => g.Name == "Pop"), Price = 8.99M, Author = authors.Single(a => a.Name == "Various authors"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Sambas De Enredo 2001", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Various authors"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Vozes do MPB", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Various authors"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Contraband", Tag = tags.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Velvet Revolver"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Vinicius De Moraes", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Vinícius De Moraes"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bach: Goldberg Variations", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Wilhelm Kempff"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bartok: Violin & Viola Concertos", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Yehudi Menuhin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Bach: The Cello Suites", Tag = tags.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Yo-Yo Ma"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Post { Title = "Ao Vivo [IMPORT]", Tag = tags.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Zeca Pagodinho"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Posts.Add(a));
        }
    }
}